config/routes.rb
IdeaExchange::Application.routes.draw do

  resources :tags

  resources :comments

  resources :ideas

  resources :locations

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy', :as => 'destroy_user_session_get'
  end

  devise_for :users

  resources :users

  match '/auth/:provider/callback' => 'authentications#create'

  resources :authentications, :only => [:index, :destroy]

  root :to => 'pages#home'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :ok }
    end
  end
end

app/views/tags/_form.html.haml
= form_for(@tag) do |f|
  - if @tag.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@tag.errors.count, 'error')} prohibited this user from being saved:"
      %ul
      - @tag.errors.full_messages.each do |msg|
        %li= msg
  
  .field
    = f.label :approved
    %br
    = f.check_box :approved
  .field
    = f.label :flagged
    %br
    = f.check_box :flagged
  .field
    = f.label :title
    %br
    = f.text_field :title

  .actions
    = f.submit

app/views/tags/edit.html.haml
%h1= t '.title'
%p
  = link_to t('back'), tags_path
  = link_to t('show'), @tag
= render 'form'

app/views/tags/index.html.haml
%h1= t('.title')
%p= link_to t('.new_tag'), new_tag_path

%table
  %thead
    %tr
      %th= Tag.human_attribute_name :approved
      %th= Tag.human_attribute_name :flagged
      %th= Tag.human_attribute_name :title
      %th{:colspan => 3}= t 'actions'
  
  %tbody
    - for tag in @tags
      %tr{ :class => cycle(:odd, :even) }
        %td= tag.approved
        %td= tag.flagged
        %td= tag.title
        %td.action= link_to t('show'), tag
        %td.action= link_to t('edit'), edit_tag_path(tag)
        %td.action= link_to t('destroy'), tag, :confirm => t('are_you_sure'), :method => :delete

app/views/tags/new.html.haml
%h1= t '.title'
%p= link_to t('back'), tags_path
= render 'form'

app/views/tags/show.html.haml
%h1= t '.title'
%p
  = link_to t('back'), tags_path
  = link_to t('edit'), edit_tag_path(@tag)

%dl
  %dt= Tag.human_attribute_name :approved
  %dd= @tag.approved
  %dt= Tag.human_attribute_name :flagged
  %dd= @tag.flagged
  %dt= Tag.human_attribute_name :title
  %dd= @tag.title